# Generated by Django 4.2.7 on 2024-01-15 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postsapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hide_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=14, null=True),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='postsapp.post')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
