# Generated by Django 4.2.7 on 2024-01-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0003_post_hide_phone_number_post_phone_number_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.TextField(blank=True, max_length=14, null=True),
        ),
    ]
