# Generated by Django 4.2.7 on 2024-01-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('usersapp', '0004_adminuser_is_admin_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='auth_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
