# Generated by Django 4.2.7 on 2024-01-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_adminuser_auth_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
