# Generated by Django 4.2.7 on 2024-01-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0007_sellerprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='bio',
            field=models.TextField(default='Bio Required'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='contact_info',
            field=models.TextField(default='Contact info Required'),
        ),
    ]
